import type { Metadata } from "next";
import { Inter, Geist_Mono, Fira_Code } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider"


const inter = Inter({
  variable: "--font-inter",
  display: 'swap',
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-fira-code',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ThemeProvider>
        <div className={`${inter.variable} ${geistMono.variable} ${firaCode.variable} antialiased min-h-screen bg-white dark:bg-gray-900 transition-colors`}>
          {children}
        </div>
      </ThemeProvider>   
      </body>
    </html>
  );
}
